### ISSUE TITLE
JLPCB Resistor Count Mismatch

### ISSUE THREAD

**Issue by E1L3VN** [alxlab-zone66x/Bourns-601-Series-RC-Network-T-Filters#1]
Hey Alxlab, 

Thanks for the amazing work recreating these filters. I was hoping to order some boards to replace all four filters on a Macintosh Plus board that I'm attempting to repair. I haven't been able to find anywhere stocking the original part anymore.

After uploading the Gerber, BOM and PickAndPlace however I'm running into an issue on JLPCB, where the parts summary lists **1925** resistors instead of the 1930 you mention in the documentation:

![image](https://github.com/alxlab-zone66x/Bourns-601-Series-RC-Network-T-Filters/assets/121719677/20a567fd-1874-470e-9726-127b08be01a1)

Any assistance you could provide with this matter would be most appreciated.

**Comment by alxlab-zone66x** [comment]
The actual exact number of resistors for 5x panels of 24 filters is 1920. It seems that JLCPCB will add extra sometimes and it varies for whatever reason. I just did it again and it gave me different numbers again:

![image](https://github.com/alxlab-zone66x/Bourns-601-Series-RC-Network-T-Filters/assets/85719219/9dc5ec6c-b7bd-4622-8721-4fe22c670d0e)

This time with 965 caps. As long as you have at least 1920 resistors and 960 caps you should be ok.

I'll change the description to mention the minimum expected values.

**Comment by E1L3VN** [comment]
Thanks Alx! 

Appreciate the prompt clarification!
